export const PVBT_PALETTE = {
  navyDeep: "#0A1832",
  navyAlt: "#112341",
  navyLight: "#1B2E54",
  papel: "#F5F1E6",
  pedra: "#E8DFC8",
  linha: "#C9BEA1",
  neblina: "#5F5A4E",
  dourado: "#C6A35C",
  douradoDeep: "#A88847",
  tinta: "#14140F",
  tintaDeep: "#08080F",
};

export const PVBT_DATA = {
  nav: {
    logo: "PVBT",
    links: [
      { label: "ESCRITÓRIO", href: "#sobre" },
      { label: "SÓCIOS", href: "#socios" },
      { label: "CASOS", href: "#casos" },
      { label: "ÁREAS", href: "#areas" },
      { label: "FOROS", href: "#foros" },
      { label: "CONTATO", href: "#contato" },
    ],
    ctaShort: { label: "AGENDAR", href: "#contato" },
  },
  hero: {
    eyebrow: "DIREITO DESPORTIVO · DESDE 2016 · SÃO PAULO",
    wordmark: "PVBT",
    razao: "Pássaro, Vieira, Botelho & Torres",
    tagline: "Boutique jurídica do mercado do futebol.",
    photos: [
      "/demos/pvbt-advogados/hero-01-stadium-aerial.jpg",
      "/demos/pvbt-advogados/hero-03-bernabeu.jpg",
      "/demos/pvbt-advogados/hero-02-stadium-sunset.jpg",
      "/demos/pvbt-advogados/hero-05-night-floodlight.jpg",
      "/demos/pvbt-advogados/hero-04-ball-sunset.jpg",
      "/demos/pvbt-advogados/hero-06-balls-golden.jpg",
    ],
    meta: [
      { label: "ESPECIALIDADE", value: "DIREITO DESPORTIVO" },
      { label: "FUNDAÇÃO", value: "2016 · 10 ANOS" },
      { label: "RECONHECIMENTO", value: "CHAMBERS BAND 3 · 4 ANOS" },
      { label: "FOROS", value: "FIFA · CBF · CBMA · CAS" },
    ],
  },
  sobre: {
    eyebrow: "§02 / SOBRE",
    eyebrowRight: "PVBT LAW · BOUTIQUE · SP",
    headlineA: "Dez anos",
    headlineB: "no jogo.",
    sub: "Boutique do mercado do futebol — atletas, clubes, intermediários e marcas.",
    body: "Fundada em 2016 por sócios com décadas de bastidor em Grêmio, São Paulo FC e Traffic Sports, a PVBT opera no triângulo entre clubes, atletas e instituições — do contrato individual à disputa internacional na FIFA e no CAS.",
    bodyItalic: "Não somos generalistas: trabalhamos um mercado só, e o trabalhamos por inteiro.",
    cifras: [
      { num: "10", unit: "ANOS", cap: "de prática contínua" },
      { num: "4", unit: "SÓCIOS", cap: "atendimento direto" },
      { num: "3", unit: "BAND CHAMBERS", cap: "Sports Law Brazil" },
      { num: "50+", unit: "CASOS FIFA · CAS", cap: "internacionais" },
    ],
  },
  socios: {
    eyebrow: "§03 / SÓCIOS",
    eyebrowRight: "TRÊS NOMES · UM TIME",
    headlineA: "Três sócios.",
    headlineB: "Um mesmo bastidor.",
    sub: "Décadas somadas em Grêmio, São Paulo FC, Traffic Sports e Roc Nation. Hoje, partners da boutique.",
    list: [
      {
        name: "Rafael Botelho",
        role: "FOUNDING PARTNER",
        creds: "Chambers Band 2 — Sports Law\nnegociações domésticas + internacionais\ntransferências e disputas FIFA",
        photo: "/demos/pvbt-advogados/socios/rafael-botelho.jpg",
      },
      {
        name: "Flavio Torres",
        role: "PARTNER",
        creds: "FIFA Executive Programme\nAnti-Doping · contencioso esportivo\narbitragem CBMA e CAS",
        photo: "/demos/pvbt-advogados/socios/flavio-torres.jpg",
      },
      {
        name: "Vinícius Lucílio",
        role: "PARTNER",
        creds: "operações · contratos\nárea consultiva\ngestão e governança",
        photo: "/demos/pvbt-advogados/socios/vinicius-lucilio.jpg",
      },
    ],
  },
  casos: {
    eyebrow: "§04 / CASOS",
    eyebrowRight: "TRÊS MARCOS · UM TRACK RECORD",
    headlineA: "Casos que",
    headlineB: "definem o mercado.",
    sub: "Transferências recorde, disputas internacionais, aconselhamento direto a atletas e clubes — do contrato à arbitragem na FIFA e no CAS.",
    list: [
      {
        label: "CASO 01 · TRANSFERÊNCIA",
        name: "Endrick",
        path: "Palmeiras → Real Madrid",
        cifra: "€ 35M",
        cifraSub: "+ €25M variáveis · 2024",
        body: "Aconselhamento à carreira do jovem atacante, via Roc Nation — desde os primeiros contratos no Palmeiras à transferência recorde pro Real Madrid.",
        photo: "/demos/pvbt-advogados/casos/endrick-juntos.jpg",
        fit: "cover" as const,
      },
      {
        label: "CASO 02 · ARBITRAGEM FIFA",
        name: "Tractor SC",
        path: "Disputa internacional · Irã ↔ Brasil",
        cifra: "€ 1.2M",
        cifraSub: "obtidos em sentença FIFA · 2022-23",
        body: "Atuação no contencioso FIFA — disputa de remuneração devida em transferência internacional, com sentença favorável e execução conduzida pela boutique.",
        photo: "/demos/pvbt-advogados/casos/tractor-sc.png",
        fit: "contain" as const,
      },
      {
        label: "CASO 03 · TRANSFERÊNCIA",
        name: "Lucas Paquetá",
        path: "West Ham → Flamengo · R$ 260M",
        cifra: "€ 42M",
        cifraSub: "retorno ao Brasil · 2025",
        body: "Aconselhamento na transferência de retorno ao futebol brasileiro — uma das maiores operações de 2025, com estrutura híbrida fixos + bônus de performance até 2028.",
        photo: "/demos/pvbt-advogados/casos/paqueta-flamengo.jpg",
        fit: "cover" as const,
      },
    ],
  },
  areas: {
    eyebrow: "§05 / ÁREAS",
    eyebrowRight: "QUATRO FRENTES · UM SÓ MERCADO",
    headlineA: "Quatro frentes.",
    headlineB: "Um só campo.",
    sub: "Do contrato individual à arbitragem internacional. Da consultoria diária à disputa institucional. PVBT atende todo o ecossistema do futebol.",
    pilares: [
      { num: "01", name: "Atletas", desc: "Representação contratual, gestão de carreira, transferências domésticas e internacionais, direitos de imagem." },
      { num: "02", name: "Clubes", desc: "Aconselhamento institucional, aquisição e venda de direitos, compliance e governança esportiva." },
      { num: "03", name: "Intermediários", desc: "Agentes FIFA, intermediação de transferências, conformidade com RSTP e regulamentos nacionais." },
      { num: "04", name: "Marcas", desc: "Patrocínio, licenciamento, direitos de mídia, naming rights e estruturação de ativos esportivos." },
    ],
    complementares: [
      { name: "Direito Tributário", desc: "tributação de atletas e clubes" },
      { name: "Direito Empresarial", desc: "sociedades, M&A esportivas" },
      { name: "Direito Cível e Contratual", desc: "contratos atípicos e atípicos" },
      { name: "Arbitragem Internacional", desc: "FIFA, CAS Lausanne, CBMA" },
      { name: "Direito Trabalhista", desc: "treinadores, comissão técnica" },
      { name: "Entretenimento e Mídia", desc: "produção, direitos audiovisuais" },
      { name: "Compliance e Integridade", desc: "anti-doping, anti-corrupção" },
      { name: "Direito Internacional", desc: "tratados, jurisdição esportiva" },
    ],
  },
  foros: {
    eyebrow: "§06 / FOROS",
    eyebrowRight: "ONDE A PVBT ATUA · NACIONAL E INTERNACIONAL",
    headlineA: "Quatro foros.",
    headlineB: "De São Paulo a Lausanne.",
    sub: "Atuação consultiva, administrativa, arbitral e judicial — do contencioso doméstico à arbitragem internacional sobre direitos esportivos.",
    list: [
      {
        num: "FORO · 01",
        name: "FIFA",
        italic: "Federação Internacional",
        city: "Zurique · Suíça",
        desc: "Disputas de transferência, contratos internacionais, RSTP",
        photo: "/demos/pvbt-advogados/foros/fifa-hq.jpg",
        overlay: 0.7,
      },
      {
        num: "FORO · 02",
        name: "CBF",
        italic: "Confederação Brasileira",
        city: "Rio de Janeiro / Brasília",
        desc: "Recursos administrativos, regulamentos nacionais",
        photo: "/demos/pvbt-advogados/foros/cbf-brasilia.jpg",
        overlay: 0.74,
      },
      {
        num: "FORO · 03",
        name: "CBMA",
        italic: "Câmara de Mediação e Arbitragem",
        city: "São Paulo · Brasil",
        desc: "Arbitragem doméstica em direito esportivo",
        photo: "/demos/pvbt-advogados/foros/cbma-saopaulo.jpg",
        overlay: 0.78,
      },
      {
        num: "FORO · 04",
        name: "CAS",
        italic: "Court of Arbitration for Sport",
        city: "Lausanne · Suíça",
        desc: "Última instância internacional em arbitragem esportiva",
        photo: "/demos/pvbt-advogados/foros/cas-lausanne.jpg",
        overlay: 0.72,
      },
    ],
  },
  equipe: {
    eyebrow: "§07 / EQUIPE",
    eyebrowRight: "TIME ENXUTO · ATENDIMENTO DIRETO",
    headlineA: "Sem balcão.",
    headlineB: "Quem fecha, atende.",
    body: "PVBT é boutique por opção — não por estágio. Cada cliente é tratado por um sócio do início ao fim, sem corredor de associados, sem call center, sem intermediação entre o titular do caso e a estratégia da disputa.",
    bodyItalic: "É assim que conseguimos sustentar dez anos de boutique e quatro anos consecutivos no Chambers Global.",
    signature: "— Manifesto operacional · PVBT",
    cifras: [
      { num: "3", label: "SÓCIOS ATIVOS", cap: "Rafael Botelho · Flavio Torres · Vinícius Lucílio" },
      { num: "1:1", label: "ATENDIMENTO", cap: "cliente / sócio · sem corredor de associados" },
      { num: "10", label: "ANOS DE BOUTIQUE", cap: "fundada em 2016 · 4 anos Chambers Global" },
    ],
  },
  contato: {
    eyebrow: "§08 / CONTATO",
    eyebrowRight: "ATENDIMENTO DIRETO · POR AGENDAMENTO",
    headlineA: "Vamos",
    headlineB: "conversar.",
    tel: "(11) 3071-2933",
    telHref: "tel:+551130712933",
    email: "contato@pvbtlaw.com",
    emailHref: "mailto:contato@pvbtlaw.com",
    enderecoStreet: "Rua Bandeira Paulista, 600",
    enderecoUnit: "Conj. 74 · Itaim Bibi",
    enderecoCity: "São Paulo · CEP 04532-001",
    selos: "CHAMBERS · LEGAL 500 · LEADERS LEAGUE · LEXOLOGY",
  },
  footer: {
    cols: [
      { label: "PVBT LAW", lines: ["Pássaro, Vieira,", "Botelho & Torres", "Sociedade de Advogados"] },
      { label: "CONTATO", lines: ["(11) 3071-2933", "contato@pvbtlaw.com"] },
      { label: "ESCRITÓRIO", lines: ["Rua Bandeira Paulista, 600", "Conj. 74 · Itaim Bibi", "São Paulo · 04532-001"] },
      { label: "RECONHECIMENTO", lines: ["Chambers Global · Band 3", "Legal 500", "Leaders League · Lexology"] },
    ],
    copy: "© 2026 · PVBT LAW · TODOS OS DIREITOS RESERVADOS",
    site: "Site por Nashpages · nashpages.com.br",
  },
};
